### ISSUE TITLE
No such file or directory @ rb_sysopen - seven_zip/version.txt

### ISSUE THREAD

**Issue by phoolish** [daptiv/seven_zip#24]
I am running into this error on a seperate cookbook when trying to load seven_zip metadata.rb file during a chefspec converge.  Have any suggestions on how to solve this?

**Comment by sneal** [comment]
It looks like the SuperMarket release is missing the version.txt file which is typically put there by CI. I'll have a fix shortly.

**Comment by sneal** [comment]
Actually that doesn't make much sense. There's a guard to check if the files exists before attempting to read it.

```
ver_path = File.join(File.dirname(__FILE__), 'version.txt')
version File.exist?(ver_path) ? IO.read(ver_path).chomp : '2.0.0'
```

Which version of the seven_zip cookbook are you using?

**Comment by phoolish** [comment]
Sorry about that.  I figured it out.  One of our devs wrote a 

```allow(File).to receive(:exist?).and_return(true)```

without specifying scope.
