### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by eehaight** [daptiv/seven_zip#27]
Two warnings are appearing when converging with this recipe (using ChefDK version 0.15.15 and chef-client 12.11.18):

 WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.

WARN: Please use the package resource available in Chef Client 12.6.
windows_package will be removed in the next major version release

**Comment by sneal** [comment]
It appears the package resource doesn't have a checksum resource attribute. I haven't looked at the download implementation of the package resource, but it doesn seem different than windows_package. Might make sense to break out a separate remote_file resource so a checksum can be verified.

**Comment by sneal** [comment]
Moving this cookbook to a new [org](https://github.com/windowschefcookbooks/seven_zip). If you get this all working please submit a PR there, thanks!
